name: CD

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'src/main.ino'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Lint Backend Code
      uses: ./.github/actions/setup-arduino-cli

    - name: Build
      run: |
        mkdir -p release
        arduino-cli compile --fqbn arduino:avr:uno src/main.ino --output-dir release/
        TAG_NAME=${GITHUB_REF#refs/tags/}
        mv release/main.ino.hex release/rfid-access-control-${TAG_NAME}.hex

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
